export const ChANGE_CURRENT_PAGE = "CHANGE_CURRENT_PAGE";
export const CHANGE_ROOM_LIST = "CHANGE_ROOM_LIST";
export const CHANGE_TOTAL_COUNT = "CHANGE_TOTAL_COUNT";
export const CHANGE_ISLANDING = "CHANGE_ISLANDING";
